export const DIGYLOG_CITIES = [
  "Agadir",
  "Ahfir",
  "Ain Harrouda",
  "Ait Melloul",
  "Al Hoceima",
  "Asilah",
  "Azemmour",
  "Azrou",
  "Beni Mellal",
  "Benslimane",
  "Berkane",
  "Berrechid",
  "Bni Drar",
  "Bouskoura",
  "Casablanca",
  "Chefchaouen",
  "Dar Bouazza",
  "Deroua",
  "El Jadida",
  "Errachidia",
  "Essaouira",
  "Fes",
  "Fnideq",
  "Guelmim",
  "Ifrane",
  "Inezgane",
  "Jerada",
  "Kenitra",
  "Khemisset",
  "Khenifra",
  "Khouribga",
  "Ksar El Kebir",
  "Laayoune",
  "Larache",
  "M'diq",
  "Marrakech",
  "Martil",
  "Meknes",
  "Mohammedia",
  "Nador",
  "Ouarzazate",
  "Ouazzane",
  "Oued Zem",
  "Oujda",
  "Rabat",
  "Safi",
  "Sale",
  "Sefrou",
  "Settat",
  "Sidi Bennour",
  "Sidi Kacem",
  "Sidi Slimane",
  "Skhirat",
  "Tanger",
  "Tan-Tan",
  "Taourirt",
  "Taroudant",
  "Taza",
  "Temara",
  "Tetouan",
  "Tiflet",
  "Tiznit",
  "Youssoufia",
  "Zagora"
] as const;

export type DigylogCity = typeof DIGYLOG_CITIES[number];
