export const DIGYLOG_CITIES = [
  "AGHBALOU N'CERDAN",
  "Abaynou",
  "Addiss",
  "Afourar",
  "Agadir",
  "Agdz",
  "Aghmat",
  "Aghzdisse",
  "Aglou",
  "Agouim",
  "Agouray",
  "Aguelmous ( khenifra )",
  "Aguelmouss ( Marrakech )",
  "Aguim",
  "Aguinane",
  "Ahdil",
  "Ahfir",
  "Ahiout El kohia",
  "Ain Allah",
  "Ain Arma",
  "Ain Beda",
  "Ain Chqef",
  "Ain El Aouda",
  "Ain Harrouda",
  "Ain Seddaq",
  "Ain Taoujdate",
  "Ain Tekki",
  "Ain beida",
  "Ain beida chichaoua",
  "Ain defali",
  "Ait Aiaaza",
  "Ait Aissa oubrahim",
  "Ait Baha",
  "Ait Ourir",
  "Ait Qamra",
  "Ait Yaazem",
  "Ait aamira",
  "Ait ben hadou",
  "Ait hadi",
  "Ait melloul",
  "Ait youssef ou ali",
  "Ajdir",
  "Ajdir Igzennayen",
  "Akhfennir",
  "Akka",
  "Akka Ighane",
  "Aklim",
  "Aknoul",
  "Al Aroui",
  "Al Hadib",
  "Al Hoceïma",
  "Al Mazar Ait melloul",
  "Amizmiz",
  "Amsa",
  "Anounfeg",
  "Anza",
  "Anzi",
  "Aouchtame",
  "Aoufous",
  "Aoulouz",
  "Aourir",
  "Arfoud",
  "Asjen",
  "Asni",
  "Assa",
  "Assahrij",
  "Assaki Taliouine",
  "Assilah",
  "Azemmour",
  "Azilal",
  "Azla",
  "Azrarag",
  "Azrou",
  "Azrou ait melloul",
  "Aéroport international Agadir",
  "Aïn Atig",
  "Aïn Bni Mathar",
  "Aïn Cheggag",
  "Aïn Dorij",
  "Aïn Karma",
  "Aïn Sfa",
  "Aït Ishaq",
  "BELAAGUID",
  "Baakila",
  "Bab Berred",
  "Bab Marzouka",
  "Bab Taliouane - Tétouan",
  "Bab Taza",
  "Barakat hssina",
  "Bejaâd",
  "Bel Ksiri",
  "Belfaa",
  "Ben Ahmed (Berchid)",
  "Ben Guerir",
  "Ben Rahmoun",
  "Ben Rahmoun marrakech",
  "Ben Taïeb",
  "Ben Yakhlef",
  "Beni ensar",
  "Beni quolla",
  "Bensergao",
  "Benslimane",
  "Berkane",
  "Berrechid",
  "Bhalil",
  "Biougra",
  "Bir Jdid",
  "Bir Tam Tam",
  "Biriz",
  "Bni Bouayach",
  "Bni Boufrah",
  "Bni Chiker",
  "Bni Drar",
  "Bni Hadifa",
  "Bni Zoli",
  "Bni khlef eljadia",
  "Boderbala",
  "Borj Agharghar",
  "Bouaassida",
  "Bouanane",
  "Bouarfa",
  "Bouarg",
  "Boudinar",
  "Boudnib",
  "Boufakrane",
  "Bouguedra",
  "Bouizakarne",
  "Boujdour",
  "Boujniba",
  "Boukidan",
  "Boulanouare",
  "Boulemane",
  "Boumalne-Dadès",
  "Boumia",
  "Boured",
  "Bouskoura",
  "Bouyafar",
  "Bouznika",
  "Bradia",
  "Brikcha",
  "Briyech",
  "Bzat",
  "Bzou",
  "Béni Mellal",
  "Cabo Negro",
  "Cafémaure",
  "Casablanca",
  "Chefchaouen",
  "Chellalate",
  "Chichaoua",
  "Chrifia Marrakech",
  "Chwiref eljadida",
  "Chwiter",
  "DOUAR CHHAB",
  "Dakhla",
  "Daouar tajin",
  "Daouar tikni",
  "Dar 40",
  "Dar El Kebdani",
  "Dar Gueddari",
  "Dar Oum Sultan",
  "Dar bouazza",
  "Dardara",
  "Dayedaate",
  "Dcheira El Jihadia",
  "Demnate",
  "Deroua",
  "Dkhissa",
  "Dlalha",
  "Douar wald El aisase",
  "Drargua",
  "Driouch",
  "EL BAHARA",
  "EL Jadida",
  "Echemmaia",
  "El Aargoube",
  "El Aarjate",
  "El Aioun Oriental",
  "El Aouamra",
  "El Aïoun Sidi Mellouk",
  "El Borouj",
  "El Boura",
  "El Gara",
  "El Hajeb",
  "El Hanchane",
  "El Houmer",
  "El Kelaâ des Sraghna",
  "El Ksiba",
  "El Maader El Kabir",
  "El Mansouria",
  "El Marsa (Laayoune)",
  "El Menaadla El jadida",
  "El Menzeh",
  "El Menzel",
  "El Mghassiyine",
  "El Ouatia (Tan-Tan)",
  "El bouchtiaine",
  "El kebab",
  "El kharij",
  "Elbarj ( Khenifra )",
  "Er-Rich",
  "Errachidia",
  "Errahma",
  "Es-Semara",
  "Essaouira",
  "Farkhana",
  "Fes",
  "Fezouane",
  "Figuig",
  "Fnideq",
  "Foum EL Hassane",
  "Foum Jemaa",
  "Foum Zguid",
  "Fquih Ben Salah",
  "Ghazoua",
  "Goulmima",
  "Guelmim",
  "Guercif",
  "Gueznaia",
  "Guigou",
  "Had Bouhssoussen",
  "Had El Brachoua",
  "Had Kourt",
  "Had oulad jelloul",
  "Haj Kaddour",
  "Harhoura",
  "Hassi al bagar",
  "Hattane",
  "Houara",
  "Houara tanger",
  "Howara",
  "Hrara",
  "Idaousmlal",
  "Idouirane",
  "Ifrane",
  "Igherm",
  "Ighoud",
  "Igoudar",
  "Ikhourbane",
  "Imi Imqqurn",
  "Imider",
  "Imintanoute",
  "Imouzzer Kandar",
  "Imzouren",
  "Inezgane",
  "Isafen",
  "Issafn TATA",
  "Issaguen",
  "Issen",
  "Itzer",
  "Izemmouren",
  "Jamâat Shaim",
  "Jaâdar",
  "Jdour",
  "Jemâa Feddalat",
  "Jerada",
  "Jorf El Melha",
  "Jorf Lasfar",
  "Kantina",
  "Karia ba mohamed",
  "Kariat Arekmane",
  "Kasba Tadla",
  "Kasbah El Taher Ait melloul",
  "Kassita",
  "Kef en Nsour",
  "Kelaat-M'Gouna",
  "Kenitra",
  "Ketama",
  "Khemis Zemamra",
  "Khenichet",
  "Khouribga",
  "Khémis Sahel",
  "Khémisset",
  "Khénifra",
  "Krona",
  "Ksar El Kébir",
  "Ksar Sghir",
  "La Nouvelle Ville Ibn Batouta",
  "La ville verte",
  "Laakarta",
  "Laakba lhamra",
  "Laamamcha",
  "Laaouina",
  "Laaouissate",
  "Laatamena el jadida",
  "Laayoune",
  "Labaarir",
  "Lagfifat",
  "Lagouassem",
  "Lahri",
  "Lakhechachena",
  "Lakhnafif",
  "Lakhssas",
  "Lakhyayeta",
  "Lalla Mimouna",
  "Lalla Takerkoust",
  "Lamriss",
  "Larache",
  "Laâtamna",
  "Lfahs el jadida",
  "Lhmadate",
  "Lkrouchiaine",
  "Lmrah",
  "Lota",
  "Loudaya",
  "Lqliâa",
  "Lâattaouia",
  "M'Hamid El Ghizlane",
  "M'rirt",
  "Madagh",
  "Majjate meknes",
  "Marina Smir",
  "Mariouari",
  "Marrakech",
  "Martil",
  "Masmouda",
  "Massa",
  "Mdiq",
  "Mechra Bel Ksiri",
  "Mediouna",
  "Mehdia",
  "Mejjat",
  "Meknes",
  "Melloussa",
  "Merchouch",
  "Merzouga",
  "Midar",
  "Midelt",
  "Mirght",
  "Mirleft",
  "Missour",
  "Mohammadia",
  "Mokrisset",
  "Moulay Abdellah Amghar",
  "Moulay Bouazza",
  "Moulay Bousselham",
  "Moulay Brahim",
  "Moulay Idriss Zerhoun",
  "Moulay Yaâcoub",
  "Msawar Rasso",
  "Msoun",
  "Mzoudia",
  "N'khakhsa",
  "Nador",
  "Nkob",
  "Nouasser",
  "Nouayl",
  "Nzalat Laadam",
  "Ouahat Sidi Brahim",
  "Oualidia",
  "Ouaouizeght",
  "Ouaoumana",
  "Ouarzazate",
  "Ouazzane",
  "Oued Amlil",
  "Oued Laabid",
  "Oued Laou",
  "Oued Zem",
  "Oujda",
  "Oulad Ayad",
  "Oulad Berhil",
  "Oulad Bou Abid",
  "Oulad Brahim ouled teima",
  "Oulad Dahou",
  "Oulad Frej",
  "Oulad Ghadbane",
  "Oulad Hassoun",
  "Oulad Jerrar",
  "Oulad Teima",
  "Oulad Yaich",
  "Oulad Youssef",
  "Oulad bourahema",
  "Oulad moussa",
  "Oulad saleh bouskoura",
  "Ouled Aarfa traoudant",
  "Ouled Aissa taroudant",
  "Ouled Aïssa",
  "Ouled Ghanem",
  "Ouled Hammou",
  "Ouled Jelal Marrakech",
  "Ouled Mbarek",
  "Ouled Settout",
  "Ouled Tayeb",
  "Ouled zekri",
  "Oum El Guerdane",
  "Ounagha",
  "Ourika",
  "Outat El Haj",
  "Plage Aghroud",
  "Port de pêche Agadir",
  "Rabat",
  "Ras El Ma",
  "Ras El Ma Fes",
  "Ras Tbouda",
  "Reggada",
  "Ribate El Kheir",
  "Rissani",
  "Rommani",
  "Rouadi",
  "SAKA guercif",
  "Sabaa Aiyoun",
  "Sad rouida",
  "Safi",
  "Sala Al Jadida",
  "Sale",
  "Saniat berghig",
  "Saïdia",
  "Saïss",
  "Sbiaat",
  "Sebt Ait Rahhou",
  "Sebt Ben Sassi",
  "Sebt El Guerdane",
  "Sebt Gezoula",
  "Sebt Jahjouh",
  "Sebt Mzouda",
  "Segangan",
  "Selouane",
  "Settat",
  "Sid L'Mokhtar",
  "Sidi Abdallah Ghiat",
  "Sidi Abed - El jadida",
  "Sidi Ali Ban Hamdouche ( Meknes )",
  "Sidi Ali Ban Hamdouche eljadida",
  "Sidi Allal El Bahraoui",
  "Sidi Allal Tazi",
  "Sidi Ayache",
  "Sidi Bennour",
  "Sidi Bettache",
  "Sidi Bibi",
  "Sidi Bou Othmane",
  "Sidi Bouknadel",
  "Sidi Boumoussa",
  "Sidi Bousberr",
  "Sidi Bouzid - El jadida",
  "Sidi El Ayedi",
  "Sidi Ettiji",
  "Sidi Hajjaj (tit mellil - Casa)",
  "Sidi Harazem",
  "Sidi Hejjaj (ben ahmed)",
  "Sidi Ifni",
  "Sidi Jaber",
  "Sidi Kacem",
  "Sidi Khiar Kandar",
  "Sidi Moussa Ben Ali",
  "Sidi Moussa El Mejdoub",
  "Sidi Moussa Lhamri",
  "Sidi Moussa Marrakech",
  "Sidi Redouane",
  "Sidi Rehal",
  "Sidi Slimane",
  "Sidi Smaïl",
  "Sidi Taibi",
  "Sidi Yahya El Gharb",
  "Sidi Yahya Zaër",
  "Sidi Zouine",
  "Sidi al kamel",
  "Sidi ali borekba",
  "Sidi bouzid chichaoua",
  "Sidi chiker",
  "Sidi sliman Mol kifan",
  "Skhinat fes",
  "Skhirate",
  "Skhour Rehamna",
  "Skoura ( ouarzazate )",
  "Smimou",
  "Souani",
  "Souihla",
  "Souiria",
  "Souk El Arbaa",
  "Souk El Had Zerkten",
  "Souk Sebt Oulad Nemma",
  "Souk tlet du gharb",
  "Séfrou",
  "TIGENZIWINE",
  "Taddart ANZA",
  "Taddart guercif",
  "Taddarte Tichka",
  "Tadouart tiznit",
  "Tadouarte agadir",
  "Tafersit",
  "Tafetachte",
  "Tafoughalt",
  "Tafraout",
  "Tafraout N'Lakhsass",
  "Tagadirt",
  "Taghazout",
  "Taghezout ouarzazate",
  "Taghzirt",
  "Tagmout",
  "Tagounite",
  "Tahanaout",
  "Tahla",
  "Tala Youssef",
  "Taliouine",
  "Talmest",
  "Talnif",
  "Taloust",
  "Talsint",
  "Tamait Izder",
  "Tamallalt",
  "Tamanar",
  "Tamansourt",
  "Tamaris",
  "Tamawanza",
  "Tamegroute",
  "Tamernout",
  "Tameslouht",
  "Tamesna",
  "Tamesna Meknes",
  "Tamezmoute",
  "Tamrabet",
  "Tamsamane",
  "Tan-Tan",
  "Tanant azilal",
  "Tanger",
  "Taouloukoult",
  "Taounate",
  "Taourirt",
  "Tarfaya",
  "Targuist",
  "Taroudannt",
  "Tarrast",
  "Tassoultante",
  "Tata",
  "Taza",
  "Tazarine",
  "Tazarte",
  "Tazenakht",
  "Temara",
  "Temsia",
  "Tendrara",
  "Teroual",
  "Tetouan",
  "Thine Riate",
  "Tiflet",
  "Tighassaline",
  "Tighirt TIZNIT",
  "Tighza",
  "Tigmi N Bobker",
  "Tiguert",
  "Tikiouine",
  "Timatraouine",
  "Timezgadiouine",
  "Tin Mansour",
  "Tinejdad",
  "Tinghir",
  "Tinzouline",
  "Tissa",
  "Tissint TATA",
  "Tit Mellil",
  "Tizi N'Tichka",
  "Tizi Ouasli",
  "Tiznit",
  "Tiztoutine",
  "Tlat Loulad",
  "Tnine Chtouka - El jadida",
  "Touama",
  "Toufliht",
  "Victoria Bouskoura",
  "Wlad hssin eljadida",
  "Youssoufia",
  "Zag",
  "Zagora",
  "Zaouïat Cheikh",
  "Zaïda",
  "Zaïo",
  "Zeghanghane",
  "Znada",
  "Zoumi",
  "agouram",
  "ain aicha",
  "ait ali",
  "ait botayeb",
  "ait mimoun",
  "asrir",
  "chrafate chefchaouen",
  "dar Ouled Zidouh",
  "had oulad zbayer",
  "had soualem",
  "heyout chair",
  "idelsan",
  "ighrissen",
  "ihchach CHTOUKA",
  "inchaden",
  "kasbat Ayir",
  "khayz",
  "khmis dades",
  "laaroumiate",
  "laqsabi",
  "lborj - Oulad teima",
  "lkharba",
  "niya",
  "okhrib",
  "ouaaroun",
  "ras el ma ifrane",
  "sidi massoud sidi maarouf",
  "takad",
  "tassaout",
  "tighmert",
  "tin amara"
] as const;

export type DigylogCity = typeof DIGYLOG_CITIES[number];